project_id = "mxtsdgkwzjzlttpotole"

[db]
major_version = 15

[functions]
  # Default; set per-function below if needed
  # verify_jwt = false

[functions.stripe]
  verify_jwt = true

[functions.ai-router]
  verify_jwt = false

[functions.openai-assistant]
  verify_jwt = false

[functions.openai-chat]
  verify_jwt = false
