// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptnrwrgzrsbocgxlpvhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0bnJ3cmd6cnNib2NneGxwdmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNDY0MTYsImV4cCI6MjA1NzkyMjQxNn0.--EOILmgTdPD2uZxu3LcLuSDXsYWV9ElhGPI5m4Ng-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});